{% set version = "0.2.3" %}

package:
  name: pydicth5
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyDictH5/pyDictH5-{{ version }}.tar.gz
  sha256: 0519a562151ca41d0c45e68397aa34b228a2c3baaa9bfd96ec9046e27c9852b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - h5py
    - numpy
    - python

test:
  imports:
    - pyDictH5

about:
  home: http://github.com/lkilcher/pyDictH5
  license: Apache
  license_file: LICENSE.txt
  license_family: APACHE
  # missing file
  # license_file: 
  summary: Standardized compound data structures for Python

extra:
  recipe-maintainers:
    - ocefpaf
