{% set version = "0.2.3" %}

package:
  name: pydicth5
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyDictH5/pyDictH5-{{ version }}.tar.gz
  sha256: 0519a562151ca41d0c45e68397aa34b228a2c3baaa9bfd96ec9046e27c9852b9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyDictH5

about:
  home: http://github.com/lkilcher/pyDictH5
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: APACHE
  summary: Standardized compound data structures for Python

extra:
  recipe-maintainers:
    - ocefpaf
