travis:
  secure:
    BINSTAR_TOKEN: OPWcBpXRGNepGnm+IQn9sfTuirRYf7VavZjDHyPqyKtfnKTa7dQAJDuesk+W+OH1xgoer0IgKxyQ+4hKU9AkPNz0kRhyUsL9Fz9ONlTaIpfEeOsoPUmYJS6Y1yPI+MbGe2i67t6hS3LT9CRYOsTuXq9vQPCCiiX7/HM1uw+KHOEyn0snXFIllblYBLOfIoaR82xYekBLTc7eJ8OaeAJQDIoBM3S2V7iYjRmubq0VH7Cuk3BFfM8hxLe4V8WuMp3ipV2DXuf7Q4F61tdJj3AGct3ijXwvXp2q2RrV1if5Ty1NEVuuKIRaHihQ5x8WivWr+NVXfptzMPcMrpJLFyVmxSfaE79SJnwvzJJaN+MHzeXpJTtxKM5kBHyJnV7gb7JQ9kmZ8EShfLoS8JXOP3Q6eNw7GZdpw2QbacQ0dm/ZHrXXpbOVRW5JHBlBPPHuuyhlbHHephpxVI65I3nzLJwVzMVfSk+1IoDAbxWW8v6ZHUZfwMxtx2OEj1KyB/KL/KnFRiEcLWUObK2dOkpVASSJHMbZFhXNG7IoS76imRgTseZOsIuA8r1EnXthc7wxLKgXdc2AHf3rbAXES0tg3O1ftz4O25YBs7cm7NgawUXSwzqbRkG4OyHYpBBrn/qrRT784YrOoF8DiVywEF/R0obpMs73MZcKs6Q66K8TISm6TDE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
