travis:
  secure:
    BINSTAR_TOKEN: GE9dZwIAcjrEYGKtp5gU26STPrBhpk0l0UIA42w57u0fUwqtZ3mJXmbsu7HpgM9H9YzgO1X4NTlO9tcpq/aSTm72vMiTcyNn2FwAIOEDoVhpCxPlpDdAw0zCFau2zMcUB1EaAJUWRSuTEYBSmJtSfzh4YU8nbr6zUjRibsDeqF/BWbY0u3k26aobdALRfOg/GU1/pEi5CY4qpQxP3KYWomOtbe7A7qHlfXGlbKIeYY4gmonkkAdv7sAhYeaVOwQ06BShU5cw5aLOsgg83CJQJMcK1/s+hZsED3FfSbckT1X1KWybi1qE8fck9sdROM2qHmMIbo6A5ipxG8dFTIMR5h+dBIwuNXpQ/Qbphr7WmOjIauEhVrNR2HVVjBCHHWpi4kGDiAeu8bXeWRGUw8AsBOTrs8/Jak6BUOZdExBPsly6AMx1gIh/L9CQJo4cB6qqxGdq9/nc8FfbzWWucyXu6ApY+HaVucBwSWe+XxTtUPU6MZb2Bf0wGa/LCDrjNyXMhfqo1+b+P8yzQ+elmz5bfSC8ZyOXHyFXydkPiruPjGhfz8z0tZ4hQhNy8PPCK+CK4Iy+ERDBrHX6wtcL+PFmGJ4Sc/NMuAQHLRazz5KK3gT9TCVm7alV/ROAvWgCXukgRgZoW5EYqZldU6cNs0T01fE3zIZnacdO6Jt92T05Tmg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
